version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: your_strong_password
    ports:
      - "3306:3306"
    restart: always
